### ISSUE TITLE
face01_no_gpuで"python example/simple.py"を実行すると"Illegal instruction"によりエラー発生(Mac OS)

### ISSUE THREAD

**Issue by yonesuke0716** [yKesamaru/FACE01_DEV#5]
はじめまして！突然の質問失礼します！
Docker hubよりface01_no_gpu:3.0.03_3をpullしてインストールする手順で進めたところ、"python example/simple.py"で"Illegal instruction"と表示され動作しません。
OSはMacのSonoma 14.7です。
Dockerのcpuを確認すると"x86_64"となっていたため、Docker DesktopのVMMの設定を確認しましたが、Rossetaは有効になっています。原因や対策にお心当たりあればご教示いただけますと幸いです。

**Comment by yKesamaru** [comment]
FACE01をご利用いただき、また詳細なエラー報告をいただき、誠にありがとうございます。

今回の「Illegal instruction」エラーに関して、主な原因として以下が考えられます

- DockerイメージはUbuntu 22.04でビルドしましたが、内部でAVXやAVX2など特定のCPU命令セットが使われているかもしれません。この場合、特にApple Silicon環境では動作しないと思います。

- MacOSのRosettaが一部のx86コードを正確に翻訳できないバグ？も存在するようです。

残念なことにこちらにMacの環境がないため、テストされたイメージをご提供するのは困難です。
（`buildx`を使えばそれらしいイメージは出来ますがテストできません…）

おそらく確実な方法はyonesuke0716様がMacOS環境でDockerイメージをビルドすることです。

以下に手順を説明いたします。

## 手順
FACE01のドキュメント：[Docker imageをビルドする](https://ykesamaru.github.io/FACE01_DEV/step_by_step/build_docker_image.html#docker-image)をあわせてご参照ください。

### リポジトリのクローン
```bash
git clone https://github.com/yKesamaru/FACE01_DEV.git
cd FACE01_DEV
```
### Dockerイメージのビルド
```bash
docker build -t <name:tag> -f docker/Dockerfile_no_gpu . --network host
```

### イメージをGUIで利用したい時
Linux環境なら`xhost +local:`コマンドを使用してDockerコンテナ内のGUIアプリケーションをホスト上で表示できますが、MacOSでは`xquartz`が必要だそうです。この部分は申し訳ないのですが分かりません。調べた限りでは以下のような感じです。
- インストール
```bash
brew install --cask xquartz
```
- ネットワーククライアントからの接続を許可
  - メニューバーの「XQuartz」→「Preferences」を選択
  - 「Security」タブを開き、「Allow connections from network clients」にチェックを入れる
  - 設定変更後、XQuartzを再起動
- `xhost`コマンド
  ```bash
  xhost + 127.0.0.1
  ```

参考：[DockerでGUIアプリケーションを開く基本的な押さえどころ](https://zenn.dev/ykesamaru/articles/add7d844f56516)

> [!NOTE]
> `xhost +`コマンドはセキュリティ上のリスクがあるため、使用後は`xhost -`を忘れないでください。

### FACE01_DEVのコンテナを起動する
カメラを接続しない場合
```bash
docker run --rm -it \
  -e DISPLAY=host.docker.internal:0 \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /path/to/host/folder:/path/to/container/folder \
  <image id>
```

ディスクを接続したい場合`-v /path/to/host/folder:/path/to/container/folder`を指定してください。

#### 仮想Python環境の有効化
```bash
. bin/activate
```

以上です。

再度、お試しいただくのは大変お手数をおかけいたしますが、引き続き何かお困りの点がございましたら、どうぞお気軽にお知らせください。サポートできるよう最善を尽くします。

改めまして、FACE01をご利用いただきましたことに深く感謝申し上げます。

**Comment by yonesuke0716** [comment]
@yKesamaru 
ご丁寧に回答いただきありがとうございます！
Dockerのビルドで以下のエラーが発生しました。

------
 > [11/24] COPY output /home/docker/FACE01_DEV/output:
------

 2 warnings found (use docker --debug to expand):
 - LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 13)
 - SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ARG "DOCKER_PASSWORD") (line 47)
Dockerfile_no_gpu:61
--------------------
  59 |     
  60 |     COPY face01lib /home/${DOCKER_USER}/FACE01_DEV/face01lib
  61 | >>> COPY output /home/${DOCKER_USER}/FACE01_DEV/output
  62 |     COPY noFace /home/${DOCKER_USER}/FACE01_DEV/noFace
  63 |     # COPY images /home/${DOCKER_USER}/FACE01_DEV/images
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref s8pltx0vkvqda3rgfwsab16dv::iojhnzd04ozcq7mi0buikpcr0: "/output": not found

確かにgit cloneした中にoutputフォルダはなかったのですが、これはコメントアウトで良いでしょうか？

**Comment by yKesamaru** [comment]
@yonesuke0716

ご報告いただき、誠にありがとうございます。

ご指摘のエラーについて、`COPY output /home/${DOCKER_USER}/FACE01_DEV/output`の行で発生している問題は、`.gitignore`ファイルに`output/*`と記載されていることが原因と考えられます。これにより、`output`ディレクトリ内のファイルがリポジトリに含まれず、ビルド時に該当ディレクトリが存在しないため、エラーが発生しています。

`output`ディレクトリは、アプリケーションの動作中に生成される画像を保存するために必要です。しかし、動作中に大量の画像が蓄積される可能性があるため、`.gitignore`に`output/*`を追加し、ディレクトリ内のファイルをバージョン管理から除外しています。ただし、`output`ディレクトリ自体は必要であるため、以下の対応をお願いいたします。

1. `Dockerfile_no_gpu`内の該当する`COPY`命令をコメントアウトしてください。

   ```dockerfile
   # COPY output /home/${DOCKER_USER}/FACE01_DEV/output
   ```

2. コンテナ起動後、以下のコマンドで`output`ディレクトリを作成してください。

   ```bash
   mkdir -p /home/${DOCKER_USER}/FACE01_DEV/output
   ```

これらの手順により、エラーを回避し、アプリケーションを正常に動作させることが可能です。

また、ビルド時に表示される以下の警告については、現時点では無視していただいて問題ありません。

- **LegacyKeyValueFormat**：`ENV`命令の形式に関する警告
- **SecretsUsedInArgOrEnv**：機密情報の取り扱いに関する警告

以上は将来的な改善点として対応します。

引き続きご不明点や問題がございましたら、お気軽にご連絡ください。

**Comment by yonesuke0716** [comment]
@yKesamaru 

ご回答ありがとうございます！
以下のライブラリが足りなかったので追加でpipインストールしたことで無事動きました！
- opencv-python
- mediapipe
- mojimoji
- onnxruntime
- scipy
- onnx
- torchvision
- requests
- tqdm

・・・と思ったら以下のようなエラーでoutputフォルダへ保存できないエラーがありました。
PermissionError: [Errno 13] Permission denied: '/home/docker/FACE01_DEV/output/安倍晋三_2024,11,15,21,21,49,401037_0.32.png'

mkdirでフォルダを作成する際、「mkdir: ディレクトリ `/home//FACE01_DEV' を作成できません: 許可がありません」
と出たため、sudoで入力したところ、ディレクトリは上手く作れたようですがデータの保存ができないようです。。
この対応はどのようにすれば良いでしょうか？

**Comment by yKesamaru** [comment]
@yonesuke0716

ご報告ありがとうございます。

手元のDockerイメージで動作確認を行いましたので、結果を共有いたします。

---
```bash
user@user:~$ docker ps -a
CONTAINER ID   IMAGE          COMMAND                   CREATED       STATUS                     PORTS     NAMES
b8ddca6a1b03   ce2952ad62d6   "/opt/nvidia/nvidia_…"   3 weeks ago   Exited (0) 3 weeks ago               admiring_mccarthy
a5f5d24d9fba   ce2952ad62d6   "/opt/nvidia/nvidia_…"   3 weeks ago   Exited (129) 3 weeks ago             beautiful_jang
056e52013385   ce2952ad62d6   "/opt/nvidia/nvidia_…"   3 weeks ago   Exited (0) 3 weeks ago               serene_ardinghelli
user@user:~$ xhost +local:
non-network local connections being added to access control list
user@user:~$ xhost
access control enabled, only authorized clients can connect
LOCAL:
SI:localuser:user
```

以下のコマンドでDockerコンテナを起動しました。

```bash
docker run -it --gpus all -e DISPLAY=$DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /home/user/ドキュメント/FACE01_mnt_Folder:/docker/ ce2952ad62d6
```

起動後の動作は以下のとおりです

```bash
==========
== CUDA ==
==========

CUDA Version 11.6.1

Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the user and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.

*************************
** DEPRECATION NOTICE! **
*************************
THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
    https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md

```

Python仮想環境を起動
```bash
docker@a847d49699fd:~/FACE01_DEV$ . bin/activate
```

コンテナ内で`output`ディレクトリが存在していることを確認しました。

```bash
(FACE01_DEV) docker@a847d49699fd:~/FACE01_DEV$ ls -al ./
合計 296
drwxr-xr-x 1 docker docker   4096  8月 18 12:32 .
drwxr-xr-x 1 docker docker   4096  8月 18 12:27 ..
-rwxrwxr-x 1 docker root     1321  8月 15 09:39 Docker_INSTALL_FACE01.sh
-rw-rw-r-- 1 docker root        0  2月 26  2023 SystemCheckLock
drwxr-xr-x 1 docker root     4096  8月 14 14:55 assets
drwxr-xr-x 3 docker docker   4096  8月 18 12:38 bin
drwxr-xr-x 4 docker docker   4096  8月 18 12:32 build
-rw-rw-r-- 1 docker root     7587  8月 17 20:25 config.ini
drwxr-xr-x 1 docker root     4096  8月 18 12:27 docs
drwxr-xr-x 1 docker root     4096  8月 18 12:27 example
drwxr-xr-x 1 docker root     4096  8月 18 12:27 face01lib
drwxr-xr-x 2 docker docker   4096  8月 18 12:27 include
drwxr-xr-x 3 docker docker   4096  8月 18 12:27 lib
lrwxrwxrwx 1 docker docker      3  8月 18 12:27 lib64 -> lib
drwxr-xr-x 1 docker root     4096  6月 24  2023 noFace
drwxr-xr-x 1 docker root   192512  8月 18 12:27 output
drwxr-xr-x 5 root   root     4096  8月 16 15:45 preset_face_images
-rw-rw-r-- 1 docker root     1089  8月 11 19:08 pyproject.toml
-rw-r--r-- 1 docker docker     70  8月 18 12:27 pyvenv.cfg
-rw-rw-r-- 1 docker root      151  8月 11 19:35 requirements_dev.txt
drwxr-xr-x 5 docker docker   4096  8月 18 12:37 share
```

`output`ディレクトリは存在し、所有者は`docker`ユーザーとなっていました。

GUIアプリケーションの起動も確認済みです。`gedit`を起動し、問題なく動作しました。

```bash
(FACE01_DEV) docker@a847d49699fd:~/FACE01_DEV$ gedit ./config.ini
```

現時点で手元の環境では`output`ディレクトリに特段の問題は見受けられませんでした。

お手数をおかけして申し訳ありません。よかったら`~/FACE01_DEV`ディレクトリ内の所有者についてご確認をお願いします。

引き続き、コンテナ内で動作に影響が出ている箇所がございましたら、再度お知らせいただけますと幸いです。

何かお気づきの点があればお気軽にご連絡ください。引き続きよろしくお願いいたします。

**Comment by yonesuke0716** [comment]
@yKesamaru 

ご検証いただきありがとうございます！
無事動作することを確認できましたので、このissueはクローズで問題ありません！
お忙しい中ご対応いただきありがとうございました！

**Comment by yKesamaru** [comment]
@yonesuke0716

ご確認いただき、またご丁寧にご連絡いただきありがとうございます！

無事に動作確認が取れたとのこと、大変嬉しく思います。
ところで、macOS上でDockerイメージを作り直していただいたとのことでしょうか？
もしその際に特別な手順や追加で行った操作などがございましたら、今後の参考としてお教えいただけますと幸いです。

改めまして、迅速なご対応とご報告、誠にありがとうございました！
また何かございましたらお気軽にご連絡ください。

**Comment by yonesuke0716** [comment]
@yKesamaru 

> macOS上でDockerイメージを作り直していただいたとのことでしょうか？

はい。ご教示いただいた通りにDockerイメージを作り直しました。
その中で追加したこととして、docker build実行前に以下2点を追加しました。

- git cloneしたFACE01_DEV直下に"output"フォルダを作成。
　→"Dockerfile_no_gpu"内のコメントアウトをしなくてよくなり、画像も保存できるようになる。
- "requirements_dev.txt"内に、上記追加pipインストールしたライブラリを追加。

この上でご教示いただいdocker build以下のことを実施することで、simple.pyの動作を確認できた次第です。

とても素晴らしいツールとモデルを無料で使わせていただいてますので、少しでもお役に立てれば幸いです。

こちらこそ改めてお礼申し上げます。
また今後もお尋ねすることがあるかもしれませんが、引き続きよろしくお願いいたします。

**Comment by yKesamaru** [comment]
@yonesuke0716

ご丁寧なご報告をいただき、誠にありがとうございます！

また、`output`フォルダの作成や`requirements_dev.txt`への追加修正など、適切な対応を施していただき、大変感謝しております。これによりスムーズに動作確認を進めていただけたとのことで、こちらも安心いたしました。

FACE01をご活用いただき、さらに貴重なフィードバックをいただけることをとても嬉しく思います。今後の改善の参考にさせていただきます！

引き続き、何かご不明点やご意見がございましたら、どうぞお気軽にお尋ねください。
改めて、素晴らしいご対応とご報告に感謝申し上げます。
